#!/bin/sh
#
# Copyright (C) 2013-2015 OpenWrt.org
#

. /lib/functions/uci-defaults.sh
. /lib/functions/system.sh

rockchip_setup_interfaces()
{
	local board="$1"

	case "$board" in
	*)
		ucidef_set_interface_lan 'eth0' 'dhcp'
		;;
	esac
}

board_config_update
board=$(board_name)
rockchip_setup_interfaces $board
board_config_flush

exit 0
